### ISSUE TITLE
UI-Kit

### ISSUE THREAD

**Issue by GrigorenkoSergey** [Van4e3WT/TOXIN#13]
Несовпадение размеров шрифтов и типов шрифтов (лучше создай папку со своими макетами, т.к. они могли поменяться; я проверял по последней версии).

![UI-KIT-colors-and-types](https://user-images.githubusercontent.com/52627852/117933355-28c55d00-b30a-11eb-999e-e58105099593.png)

**Comment by Van4e3WT** [comment]
Проверил, поменялись, Quicksand убрали совсем, теперь по всему проекту используется Montserrat. Так что буду переделывать из под Open Sans'a всё под Montserrat (еще подробно сравню с макетом на фигме)

**Comment by Van4e3WT** [comment]
> Несовпадение размеров шрифтов и типов шрифтов (лучше создай папку со своими макетами, т.к. они могли поменяться; я проверял по последней версии).


Проверил, поменялись, Quicksand убрали совсем, теперь по всему проекту используется Montserrat. Так что буду переделывать из под Open Sans'a всё под Montserrat (еще подробно сравню с макетом на фигме)

**Comment by GrigorenkoSergey** [comment]
![Screenshot from 2021-05-17 15-53-53](https://user-images.githubusercontent.com/52627852/118497347-a84d9480-b72d-11eb-9461-5a020bb5ed06.png)
Небольшие расхождения

**Comment by GrigorenkoSergey** [comment]
Небольшие расхождения в colors-and-fonts. Большие расхождения в cards. Проверь и дальше. 
![PP-cards2](https://user-images.githubusercontent.com/52627852/118497890-27db6380-b72e-11eb-980e-ca7fbecc2bed.png)

**Comment by GrigorenkoSergey** [comment]
Карточки.
1) в карточке "регистрация аккаунта" мне нужно щелкнуть  более 400 раз, чтобы ввести свою дату рождения )
2) некорректное поведение поля Гости. Не закрывается автоматически при клике вне поля. Есть какие-то мертвые зоны.

https://user-images.githubusercontent.com/52627852/118498754-08910600-b72f-11eb-96a5-6777314627cb.mp4

3) нет паддингов у инпутов справа.
4) все кнопки, с которыми взаимодействуем, должны быть с cursor: pointer (см. toggle).
