### ISSUE TITLE
Организация проекта.

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#28]
![project](https://user-images.githubusercontent.com/75975369/132092535-f6befe9e-17b0-4612-8f94-621c2eb2c146.jpg)

В папку src мы помещаем исходный код нашего проекта, т е js, css, pug и т д. Те файлы исходного кода которые мы сами пишем и редактируем. Больше там быть ничего не должно. Ожидается что она лежит в корне проета.

В папку static (или assets или public) мы помещаем статичные файлы (которые мы не редактируем), и которые отдаем какому-то статик-серверу или cdn, и получаем их в браузере как есть. Это обычно картинки, шрифты, favicon (но его иногда и в корень проекта помещают) статичный js и css если он подключается на странице напрямую. Ожидается что он лежит в корне проекта (в src ему делать нечего).

Еще мне не понятно предназначение папки project-layouts c картинками. Поясни пожалуйста зачем она?

**Comment by Van4e3WT** [comment]
> Еще мне не понятно предназначение папки project-layouts c картинками. Поясни пожалуйста зачем она?

Предыдущий ревьюер много проверял по PixelPerfect, а т.к. макет на фигме постепенно всё равно меняется, то было решено вынести макеты для сравнения с пп в папку.

**Comment by mglknFSD** [comment]
> > Еще мне не понятно предназначение папки project-layouts c картинками. Поясни пожалуйста зачем она?
> 
> Предыдущий ревьюер много проверял по PixelPerfect, а т.к. макет на фигме постепенно всё равно меняется, то было решено вынести макеты для сравнения с пп в папку.

А, ок, можешь ее оставить.

**Comment by mglknFSD** [comment]
![style](https://user-images.githubusercontent.com/75975369/132729842-eaa789fd-db93-4e92-b688-fc7875444fb7.jpg)

Зачем нужен скрипт style.js? Поясни пожалуйста.

**Comment by Van4e3WT** [comment]
> Зачем нужен скрипт style.js? Поясни пожалуйста.

Через него подключаются все стили: вспомогательные плагины air-datepicker (пакет npm), multislider-v43 (статичные css и js) ну и style.scss между прочим.
Изначально он предполагался как файл с подключением всяких css стилей, чтоб семантически было отделено, но т.к. после первого ревью из index.js многое ушло, я полагаю он в данный момент является просто ненужным промежуточным звеном и его можно убрать, а всё написать напрямую в index.js

**Comment by mglknFSD** [comment]
Не допускаются вложенные блоки. Структура должна быть плоской.

![blocs](https://user-images.githubusercontent.com/75975369/133795017-3018933d-cc3b-4af9-b7f0-b9b7e3dbeaef.jpg)

**Comment by Van4e3WT** [comment]
> Не допускаются вложенные блоки. Структура должна быть плоской.

Не совсем понял. Т.е. нельзя использовать блоки в блоках? А какой тогда вообще смысл делать блоки если они не реиспользуемы?
Если у меня, например, логотип появляется в нескольких разных блоках на странице, то мне нельзя для этого использовать блок, а нужно хардкодить вёрстку и при необходимости изменить логотип компании изменять весь хардкод вручную?

**Comment by Van4e3WT** [comment]
> Не допускаются вложенные блоки. Структура должна быть плоской.

Т.е. тут именно вопрос к файловой структуре? footer_mobile изначально подразумевался как модификация стандартного футера. Его надо вынести в отдельный блок?

**Comment by mglknFSD** [comment]
> > Не допускаются вложенные блоки. Структура должна быть плоской.
> 
> Т.е. тут именно вопрос к файловой структуре? footer_mobile изначально подразумевался как модификация стандартного футера. Его надо вынести в отдельный блок?

Да, вопрос к файловой структуре.
