### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#29]
![dev](https://user-images.githubusercontent.com/75975369/132092842-c24a0732-ab5b-4224-8950-9d8fe7c635a5.jpg)

Пакеты которые нужны только для того что бы собрать проект это devDependencies

**Comment by Van4e3WT** [comment]
> Пакеты которые нужны только для того что бы собрать проект это devDependencies

Тогда получается в dependencies останутся только jQuery и air-datepicker? Потому что по сути остальные нужны только для сборки
