### ISSUE TITLE
css

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#30]
![colors](https://user-images.githubusercontent.com/75975369/132092917-a803ad80-86a3-4e8b-9182-1a30fcc0e838.jpg)
 
1 Крайне неудачное именование переменных. Что если то, что ты называешь purple дизайнер из фиолетового сделает розовым, тебе придется вводить новую переменную и переименовывать purple в pink по всему проекту. Смысл в этой переменной в таком случае теряется. Именовать переменные нужно по смыслу. Есть главный цвет, есть второстепенный, есть для шрифта, для бэкграунда и т д. 

Шрифты то же можно поместить в переменную.

**Comment by mglknFSD** [comment]
2. Декларации шрифтов вынести в отдельный файл.

![fonrs](https://user-images.githubusercontent.com/75975369/132093051-2726119d-3cdb-4216-aaec-83878445c505.jpg)

**Comment by mglknFSD** [comment]
3. Глобальные стили по БЭМ запрещены. Разрешены только для html и body.

![globl](https://user-images.githubusercontent.com/75975369/132093143-84733b41-a625-4f26-a73d-d95a0fa21ba1.jpg)

Селектор * только для box-sizing: border-box;.

**Comment by mglknFSD** [comment]
4. Давай, все таки придем к чему-то одному. Либо ты используешь `px` либо `rem`. Если ты используешь rem то допустимо использовать px для задания толщины бордера (в rem это не слишком удобно), все остальное пожалуйста в rem-ах. Либо переведи все в px.

![rem](https://user-images.githubusercontent.com/75975369/132093248-f0804111-21da-4fd6-96ae-4a5bbd5d83ea.jpg)

**Comment by mglknFSD** [comment]
5. Почитай пожалуйста,[ правила именования модификаторов](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)  и исправь.

![modificators](https://user-images.githubusercontent.com/75975369/132093413-51a00e7d-4d76-4c7c-995f-b005e0f03094.jpg)

**Comment by mglknFSD** [comment]
6. Для чего понадобился вот такой код и почему без него никак? Поясни пожалуйста.

![ls](https://user-images.githubusercontent.com/75975369/132093659-07f89c3b-4213-4225-b915-7da42a96a645.jpg)

**Comment by mglknFSD** [comment]
7. Правило - 1 папка, 1 блок, 1 класс. Никаких других классов быть не должно.

![block](https://user-images.githubusercontent.com/75975369/132093733-447b9369-a588-4d60-9d6d-d356593f3ada.jpg)

**Comment by mglknFSD** [comment]
8. Вот так лучше не делать. SVG картинки должны хранится в .svg файлах, что бы их проще было заменить при необходимости.

![data](https://user-images.githubusercontent.com/75975369/132093834-41bc7299-a04f-428d-b0ae-9cf9eb0b3716.jpg)

**Comment by Van4e3WT** [comment]
> 1. Глобальные стили по БЭМ запрещены. Разрешены только для html и body.

Как в таком случае будет наиболее правильно решить проблему? вместо тегов задать селекторы, которые передавать каждому необходимому элементу/блоку?

> Селектор * только для box-sizing: border-box;.

А можно обнулять отступы margin, padding?

**Comment by mglknFSD** [comment]
> > 1. Глобальные стили по БЭМ запрещены. Разрешены только для html и body.
> 
> Как в таком случае будет наиболее правильно решить проблему? вместо тегов задать селекторы, которые передавать каждому необходимому элементу/блоку?
> 
> > Селектор * только для box-sizing: border-box;.
> 
> А можно обнулять отступы margin, padding?

Необходимо убрать глобальные стили, и поместить их внутрь блоков.

**Comment by Van4e3WT** [comment]
> 1. Для чего понадобился вот такой код и почему без него никак? Поясни пожалуйста.
> 
> ![ls](https://user-images.githubusercontent.com/75975369/132093659-07f89c3b-4213-4225-b915-7da42a96a645.jpg)

Для UI-kit PixelPerfect. Без него вот такое несовпадение 
![image](https://user-images.githubusercontent.com/57857742/132818738-648e29fa-7b8a-496e-b89c-94334e9331ca.png)

**Comment by Van4e3WT** [comment]
> 1. Правило - 1 папка, 1 блок, 1 класс. Никаких других классов быть не должно.
> 
> ![block](https://user-images.githubusercontent.com/75975369/132093733-447b9369-a588-4d60-9d6d-d356593f3ada.jpg)

В случае, если убрать эти модификаторы, то footer-mobile не будет отображаться в UI-kit'e на больших устройствах, а footer на маленьких, потому что у этих блоков такая модель поведения.

**Comment by mglknFSD** [comment]
> 
> 
> > 1. Правило - 1 папка, 1 блок, 1 класс. Никаких других классов быть не должно.
> > 
> > ![block](https://user-images.githubusercontent.com/75975369/132093733-447b9369-a588-4d60-9d6d-d356593f3ada.jpg)
> 
> В случае, если убрать эти модификаторы, то footer-mobile не будет отображаться в UI-kit'e на больших устройствах, а footer на маленьких, потому что у этих блоков такая модель поведения.

Я не знаю о каких модификаторах идет речь (в приведенном мной коде их вообще нету). Тут нарушение правил БЭМ - каскад запрещен. Когда вы пишите такой код 

```scss
.class-a {
    .class-b {
        ...
    }
}
```

то он превращается вот в такой 

```css
.class-a .class-b {
   ...
}
```

Когда мы ставим зависимость одних классов от других (и не только классов) это называется каскад. Это создает очень много проблем, и БЭМ, в своих правилах, уходит от каскада. И, кстати, миксины у нас запрещены. Я не понимаю при чем тут модификаторы?

**Comment by mglknFSD** [comment]
Именование модификаторов. Надо просмотреть весь код.

![modificator](https://user-images.githubusercontent.com/75975369/133794701-c34ddff8-066d-4908-9156-d2fe0506cad1.jpg)

**Comment by mglknFSD** [comment]
Тут можно использовать цикл

![for](https://user-images.githubusercontent.com/75975369/133796566-ca73b06b-d8bc-4d39-b1cc-b3b519eff32b.jpg)

**Comment by mglknFSD** [comment]
- не очень понятна семантика этой переменной
- почему она определяется в нескольких файлах?

![media_size](https://user-images.githubusercontent.com/75975369/133797267-855e890c-b6e2-415e-a253-d000b6bd4bc7.jpg)

**Comment by Van4e3WT** [comment]
> Именование модификаторов. Надо просмотреть весь код.
> 
> ![modificator](https://user-images.githubusercontent.com/75975369/133794701-c34ddff8-066d-4908-9156-d2fe0506cad1.jpg)

А что в данном случае не так?

> Модификатор — должен удовлетворять свойствам модификатора из английского языка. Всегда adjective или adjectival phrase.

В данном случае используется прилагательное: `block__wrapper_small = block wrapper is small`.
Т.е. за существительным следует прилагательное, описывающее состояние, вот если бы там был глагол вместо существительного, тогда бы понял в чем ошибка.
Либо как вариант более корректный adjectival phrase: `block__wrapper_size_small`

**Comment by Van4e3WT** [comment]
> * не очень понятна семантика этой переменной
> * почему она определяется в нескольких файлах?
> 
> ![media_size](https://user-images.githubusercontent.com/75975369/133797267-855e890c-b6e2-415e-a253-d000b6bd4bc7.jpg)

Тут переменная медиа-запроса исключительно в пределах блока и определяет для него значения стилей, при изменении разрешения устройства.

**Comment by mglknFSD** [comment]
> Тут переменная медиа-запроса исключительно в пределах блока и определяет для него значения стилей, при изменении разрешения устройства.

Я у тебя много таких видел, все в пределах блока все носят такое же имя и такое же значение. И я так и не понял на счет семантики этой переменной.

**Comment by Van4e3WT** [comment]
> > Тут переменная медиа-запроса исключительно в пределах блока и определяет для него значения стилей, при изменении разрешения устройства.
> 
> Я у тебя много таких видел, все в пределах блока все носят такое же имя и такое же значение. И я так и не понял на счет семантики этой переменной.

Семантика переменной - размер медиа-запроса для блока. Т.к. они все определены только в файле стилей определенного блока, то при транспиляции стилей они преобразовываются в значения соответствующие этой переменной в пределах блока.
А вот все медиа-сайзы блоков
![image](https://user-images.githubusercontent.com/57857742/134138469-94489901-e875-41da-9af1-780fc762fed6.png)

**Comment by Van4e3WT** [comment]
И вопрос насчёт именования модификаторов еще остался, который я задал выше

**Comment by mglknFSD** [comment]
> Семантика переменной - размер медиа-запроса для блока. Т.к. они все определены только в файле стилей определенного блока, то при транспиляции стилей они преобразовываются в значения соответствующие этой переменной в пределах блока.

1. Семантика - наука о смысле. Если ты задаешь в переменной размер для медиа запроса, верно было бы указать для какого именно размера он задается (Large, ExtraLarge, Mobile и так далее...). Мы задаем названия для переменных семантически, для того, что бы по названию переменной нам был понятен ее смысл. В переменной $mediaSize может лежать какой угодно размер, и ее семантика мне не понятна. В переменной $mediaSizeMobile я понимаю что лежит что-то вроде 320 или 480.

2. Все переменные такого рода необходимо вынести в отдельный файл и использовать глобально. (так же как цвета и шрифты)

**Comment by mglknFSD** [comment]
Все issues надо смотреть по всему проекту

![каскад](https://user-images.githubusercontent.com/75975369/134767014-dc8d4deb-d4db-4283-b5c8-3c51cb21babb.jpg)
.

**Comment by mglknFSD** [comment]
> 
> 
> > Именование модификаторов. Надо просмотреть весь код.
> > ![modificator](https://user-images.githubusercontent.com/75975369/133794701-c34ddff8-066d-4908-9156-d2fe0506cad1.jpg)
> 
> А что в данном случае не так?
> 
> > Модификатор — должен удовлетворять свойствам модификатора из английского языка. Всегда adjective или adjectival phrase.
> 
> В данном случае используется прилагательное: `block__wrapper_small = block wrapper is small`.
> Т.е. за существительным следует прилагательное, описывающее состояние, вот если бы там был глагол вместо существительного, тогда бы понял в чем ошибка.
> Либо как вариант более корректный adjectival phrase: `block__wrapper_size_small`

Тут я не прав. Но еще есть места где надо исправить.

![modificators](https://user-images.githubusercontent.com/75975369/134767116-bc86b8ee-ec46-448b-92f5-1309a6db74b1.jpg)

**Comment by mglknFSD** [comment]
Глобальные стили запрещены.

![global style](https://user-images.githubusercontent.com/75975369/134767223-00276e9f-90a2-4b09-98d9-06a5ed5a0912.jpg)

**Comment by mglknFSD** [comment]
Название для переменной "темная тень" мне кажется не очень удачным, и не отражает ее семантику.

![ds](https://user-images.githubusercontent.com/75975369/134767274-64f2947b-22c7-4e0c-853e-e196bd4fe7ed.jpg)

**Comment by Van4e3WT** [comment]
> Все issues надо смотреть по всему проекту
> 
> ![каскад](https://user-images.githubusercontent.com/75975369/134767014-dc8d4deb-d4db-4283-b5c8-3c51cb21babb.jpg)

Это стили, перекрывающие стили плагина air-datepicker. Для открытого datepicker'a паддинг отличается от стандартного, тут от вложенности избавиться не получится, потому что изменить классы плагина я не могу.

Т.е. по-умолчанию для `datepicker--nav` есть какие-то стили плагина, я их перекрываю своими стилями из `datepicker-fork.js`, НО для pixelPerfect у открытого datepicker'a другие отступы, следовательно мне нужно изменять свойство `datepicker--nav` только у открытого, НО добавить свой класс в ПЛАГИН я не могу, поэтому здесь не вижу пути уйти от вложенности, потому что идёт взаимодействие со сторонним модулем.

**Comment by Van4e3WT** [comment]
> > > Именование модификаторов. Надо просмотреть весь код.
> > > ![modificator](https://user-images.githubusercontent.com/75975369/133794701-c34ddff8-066d-4908-9156-d2fe0506cad1.jpg)
> > 
> > 
> > А что в данном случае не так?
> > > Модификатор — должен удовлетворять свойствам модификатора из английского языка. Всегда adjective или adjectival phrase.
> > 
> > 
> > В данном случае используется прилагательное: `block__wrapper_small = block wrapper is small`.
> > Т.е. за существительным следует прилагательное, описывающее состояние, вот если бы там был глагол вместо существительного, тогда бы понял в чем ошибка.
> > Либо как вариант более корректный adjectival phrase: `block__wrapper_size_small`
> 
> Тут я не прав. Но еще есть места где надо исправить.
> 
> ![modificators](https://user-images.githubusercontent.com/75975369/134767116-bc86b8ee-ec46-448b-92f5-1309a6db74b1.jpg)

Здесь arrow используется в форме прилагательного "стрелочный". Но это неочевидно (в отличии от прилагательной фразы), поэтому подумаю насчёт этого

**Comment by Van4e3WT** [comment]
> Название для переменной "темная тень" мне кажется не очень удачным, и не отражает ее семантику.
> 
> ![ds](https://user-images.githubusercontent.com/75975369/134767274-64f2947b-22c7-4e0c-853e-e196bd4fe7ed.jpg)

Насколько я знаю, `shade` переводится как оттенок

**Comment by mglknFSD** [comment]
> > Название для переменной "темная тень" мне кажется не очень удачным, и не отражает ее семантику.
> > ![ds](https://user-images.githubusercontent.com/75975369/134767274-64f2947b-22c7-4e0c-853e-e196bd4fe7ed.jpg)
> 
> Насколько я знаю, `shade` переводится как оттенок

Я понимаю, но семантика не ясна. Он для чего используется-то? Для цвета шрифта? Ну почему бы его так и не назвать?

**Comment by mglknFSD** [comment]
Не семантическое именование элементов

![div](https://user-images.githubusercontent.com/75975369/138588686-9160d751-3aea-4cdb-95e6-703a083c6ceb.jpg)
