### ISSUE TITLE
 Шрифты

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#31]
[Бест практис](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#3.2)

**Comment by Van4e3WT** [comment]
> [Бест практис](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#3.2)

Т.е. нужны только woff2, woff? или оставить следующими по загрузке svg и ttf? И если их оставить, то в каком порядке?

**Comment by mglknFSD** [comment]
Все в соответствие с best practice

**Comment by Van4e3WT** [comment]
> Все в соответствие с best practice

Хорошо, тогда в соответствии с best practice такой вопрос. Нужна ли поддержка старых браузеров (в плане шрифтов)? Если нет, то вопросы по этому поводу отпадают, а так, многие вещи просто не описаны в bp.

**Comment by mglknFSD** [comment]
> > Все в соответствие с best practice
> 
> Хорошо, тогда в соответствии с best practice такой вопрос. Нужна ли поддержка старых браузеров (в плане шрифтов)? Если нет, то вопросы по этому поводу отпадают, а так, многие вещи просто не описаны в bp.

Какие браузеры нужны, какие не нужны описано в условиях задания.

**Comment by Van4e3WT** [comment]
> Какие браузеры нужны, какие не нужны описано в условиях задания.

Да действительно, но есть одна вещь, которая у меня не складывается в голове.
В условии написано:

> Ориентироваться на последние версии Chrome и Firefox. На Safari и старые IE можно не обращать внимания для этих заданий

По best practice из этого можно сделать вывод по пункту CSS 3.2:

> Если не требуется поддержка старых браузеров, шрифты должны быть в форматах .woff2, .woff. Сначала подключать .woff2 шрифты, затем — .woff

Но, при этом ниже в условии задания указано:

> Все шрифты должны быть подключены и сгенерированы в форматах .ttf, .woff, .svg, в сервисе Font2Web

Какой из них должен быть по итогу  (woff2, woff или же ttf, woff, svg)?

**Comment by mglknFSD** [comment]
Приоритет у best practice.
