### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#32]
Футер должен быть прижат к низу страницы даже если нет контента.

![footer](https://user-images.githubusercontent.com/75975369/132093972-0d3358b0-8367-4cfd-bf6c-4d83bccc24c8.jpg)

**Comment by Van4e3WT** [comment]
Футер прижимается к низу. Для этого служит обёртка main 
![image](https://user-images.githubusercontent.com/57857742/132842029-d006adfc-47cd-427f-8fb9-6db71fd3657e.png)
Она генерируется исходя из базового компонента, содержащего футер и хедер, вся контентная часть располагается в ней (обертке с тегом main).
![image](https://user-images.githubusercontent.com/57857742/132842183-ce431c71-1661-4a46-9486-ff7cac15e4e5.png)
