### ISSUE TITLE
circle diagram

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#33]
![cd](https://user-images.githubusercontent.com/75975369/132728765-8f83b491-825f-4a62-97c5-29bab9374df0.jpg)

Сейчас у тебя компонент с круговой диаграммой, отображающей отзывы, это просто svg хардкод. Но она должна работать (как и все компоненты). Т е мы должны передать в этот компонент данные о количесве голосов (в pug mixin) и компонент должен их отобразить.

**Comment by Van4e3WT** [comment]
Компонент круговой диаграммы принимает некоторые параметры, в т.ч. параметры пропорций.
![image](https://user-images.githubusercontent.com/57857742/132842967-e850c9e4-3a9c-4ee0-9e76-0188bd9ecf53.png)
Если их задать отличными от стандартных, то изменения отобразятся в вёрстке
![image](https://user-images.githubusercontent.com/57857742/132843038-0b602eaf-fa2c-4575-acdf-1acf1e9176da.png)
Достигается это путём вычисления `stroke-dasharray` и `stroke-dashoffset`
