### ISSUE TITLE
js

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#35]
- Вложенных if лучше избегать. Структуру бизнес логики приложения лучше держать плоской и последовательной, поддерживать такой код очень тяжело.
- везде где возможно необходимо использовать деструктуризацию

![if](https://user-images.githubusercontent.com/75975369/133801496-81029f83-f927-48cc-aae4-479dde7ddb2d.jpg)

**Comment by mglknFSD** [comment]
- огромный forEach callback внутри огромного init метода. Необходимо распилить.
- все хандлеры лучше хранить как методы класса.

![some](https://user-images.githubusercontent.com/75975369/133802299-deb1ddb2-be94-4fa7-ab43-85593fa2a285.jpg)

**Comment by mglknFSD** [comment]
Приведение типов лучше делать явно.

![type](https://user-images.githubusercontent.com/75975369/133803285-f8903825-b0ab-4812-ab82-9b95f6fbd016.jpg)

**Comment by mglknFSD** [comment]
Вся бизнес логика компонентов должна хранится в классах. В инициализирующих скриптах должна располагаться только инициализация или функция в которой происходит инициализация и ее импорт.

![b](https://user-images.githubusercontent.com/75975369/133803741-4812af13-68db-4b2a-851b-6e5fffa2e690.jpg)

**Comment by mglknFSD** [comment]
- именование файла
- бизнес логика хранится в классах



![naming](https://user-images.githubusercontent.com/75975369/134766893-cc83894d-ef65-4937-9cad-841ac54f0a98.jpg)

По поводу именования (кажется я оставлял подобный issue но продублирую если этого не делал). Инициализирующий файл блока либо `index.js` или `opened-datepick.js` (так же как блок). Нужно выбрать что-то одно и следовать этому правилу. Вся бизнес логика хранится в классах. Файл с классом называется так же как класс. В инициализирующий файлах только инициализация. Пример что-то вроде такого. 

```js
import 'somethig';

function init(someArgument) {
   const someComponent = SomeComponent({someArgument: someArgument});
   
   someComponent.init();
}

export default init;
```

**Comment by Van4e3WT** [comment]
> Вся бизнес логика хранится в классах. Файл с классом называется так же как класс. В инициализирующий файлах только инициализация. Пример что-то вроде такого.
> 
> ```js
> import 'somethig';
> 
> function init(someArgument) {
>    const someComponent = SomeComponent({someArgument: someArgument});
>    
>    someComponent.init();
> }
> 
> export default init;
> ```

Класс является обязательным условием хранения логики или можно использовать импортируемую функцию? Не будет ли выглядеть громоздко и излишне создание класса для выполнения такого куска кода?
```
$('.js-opened-datepick').each((i, el) => {
  $(el).datepicker({
    inline: true,
    ...airDatepickerConfig,
  });

  hideByApply.call($(el).data('datepicker'));
});
```

**Comment by mglknFSD** [comment]
> 
> 
> > Вся бизнес логика хранится в классах. Файл с классом называется так же как класс. В инициализирующий файлах только инициализация. Пример что-то вроде такого.
> > ```js
> > import 'somethig';
> > 
> > function init(someArgument) {
> >    const someComponent = SomeComponent({someArgument: someArgument});
> >    
> >    someComponent.init();
> > }
> > 
> > export default init;
> > ```
> 
> Класс является обязательным условием хранения логики или можно использовать импортируемую функцию? Не будет ли выглядеть громоздко и излишне создание класса для выполнения такого куска кода?
> 
> ```
> $('.js-opened-datepick').each((i, el) => {
>   $(el).datepicker({
>     inline: true,
>     ...airDatepickerConfig,
>   });
> 
>   hideByApply.call($(el).data('datepicker'));
> });
> ```

Я не думаю, что это выглядело громоздко в классе, но можно оставить функцией.

**Comment by mglknFSD** [comment]
Именование. i, j и прочие подходят для именования счетчика в цикле for, так исторически сложилось. В forEach, map и им подобных лучше использовать index. Так понятнее.

![i](https://user-images.githubusercontent.com/75975369/138588398-d50d9497-5b05-42dc-ab40-f5c09233c800.jpg)

**Comment by mglknFSD** [comment]
Составной предикат 

![predicat](https://user-images.githubusercontent.com/75975369/138588467-995bef8e-9f3f-46b4-a8c3-5cffda2abe9a.jpg)

**Comment by mglknFSD** [comment]
Проблема этого кода что он будет выполняться при любом импорте файла. И по сути даже если у тебя нету на странице дропдаунов - он все равно выполнится. Для того что бы иметь контроль мы выносим подобный код вверх, на страницу где он будет выполняться.

![event_listener](https://user-images.githubusercontent.com/75975369/138588483-f785eb90-40dd-4309-8c37-c6cb7e1bbebb.jpg)

**Comment by Van4e3WT** [comment]
> Проблема этого кода что он будет выполняться при любом импорте файла. И по сути даже если у тебя нету на странице дропдаунов - он все равно выполнится. Для того что бы иметь контроль мы выносим подобный код вверх, на страницу где он будет выполняться.
> 
> ![event_listener](https://user-images.githubusercontent.com/75975369/138588483-f785eb90-40dd-4309-8c37-c6cb7e1bbebb.jpg)

1) Убрать навешивание события `DOMContentLoaded` (в данном случае dropdown-relative.js)
2) Экспортировать по умолчанию эту инициализирующую функцию (внутри файла dropdown-relative.js)
3) В модуле, в котором происходит импорт этого модуля (т.е. в form-elements.js) прописать, что-то типо:
```javascript
import DropdownRelativeInit from 'Blocks/dropdown-relative/dropdown-relative'; // импорт блока, который требует инициализации
import 'Blocks/some-module';
// и т.п. импорты

const initForm = () => {
  DropdownRelativeInit();
  // и т.д. тут могут вызываться еще другие такие инициализаторы
};

export default initForm; // и так до уровня страницы прокидываем и только в скриптовом файле страницы вызываем навешивание `DOMContentLoaded`
```

Я правильно понял?
Просто показал на примере `dropdown-relative` и `form-elements` (понятно что надо исправлять по всему проекту)

**Comment by mglknFSD** [comment]
> 
> 
> > Проблема этого кода что он будет выполняться при любом импорте файла. И по сути даже если у тебя нету на странице дропдаунов - он все равно выполнится. Для того что бы иметь контроль мы выносим подобный код вверх, на страницу где он будет выполняться.
> > ![event_listener](https://user-images.githubusercontent.com/75975369/138588483-f785eb90-40dd-4309-8c37-c6cb7e1bbebb.jpg)
> 
>     1. Убрать навешивание события `DOMContentLoaded` (в данном случае dropdown-relative.js)
> 
>     2. Экспортировать по умолчанию эту инициализирующую функцию (внутри файла dropdown-relative.js)
> 
>     3. В модуле, в котором происходит импорт этого модуля (т.е. в form-elements.js) прописать, что-то типо:
> 
> 
> ```js
> import DropdownRelativeInit from 'Blocks/dropdown-relative/dropdown-relative'; // импорт блока, который требует инициализации
> import 'Blocks/some-module';
> // и т.п. импорты
> 
> const initForm = () => {
>   DropdownRelativeInit();
>   // и т.д. тут могут вызываться еще другие такие инициализаторы
> };
> 
> export default initForm; // и так до уровня страницы прокидываем и только в скриптовом файле страницы вызываем навешивание `DOMContentLoaded`
> ```
> 
> Я правильно понял? Просто показал на примере `dropdown-relative` и `form-elements` (понятно что надо исправлять по всему проекту)

Да, ты все верно понял.

**Comment by Van4e3WT** [comment]
> > > Проблема этого кода что он будет выполняться при любом импорте файла. И по сути даже если у тебя нету на странице дропдаунов - он все равно выполнится. Для того что бы иметь контроль мы выносим подобный код вверх, на страницу где он будет выполняться.
> > > ![event_listener](https://user-images.githubusercontent.com/75975369/138588483-f785eb90-40dd-4309-8c37-c6cb7e1bbebb.jpg)
> > 
> > 
> > ```
> > 1. Убрать навешивание события `DOMContentLoaded` (в данном случае dropdown-relative.js)
> > 
> > 2. Экспортировать по умолчанию эту инициализирующую функцию (внутри файла dropdown-relative.js)
> > 
> > 3. В модуле, в котором происходит импорт этого модуля (т.е. в form-elements.js) прописать, что-то типо:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > import DropdownRelativeInit from 'Blocks/dropdown-relative/dropdown-relative'; // импорт блока, который требует инициализации
> > import 'Blocks/some-module';
> > // и т.п. импорты
> > 
> > const initForm = () => {
> >   DropdownRelativeInit();
> >   // и т.д. тут могут вызываться еще другие такие инициализаторы
> > };
> > 
> > export default initForm; // и так до уровня страницы прокидываем и только в скриптовом файле страницы вызываем навешивание `DOMContentLoaded`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Я правильно понял? Просто показал на примере `dropdown-relative` и `form-elements` (понятно что надо исправлять по всему проекту)
> 
> Да, ты все верно понял.

Переделывая под этот формат, я понял, что работает это не так как задумывалось, потому что всё собирается в один JS файл и получается, что срабатывает несколько хендеров на каждой странице. Я так полагаю, что надо для каждой страницы теперь сделать отдельную генерацию скриптового JS файла, чтобы это работало как надо?

**Comment by mglknFSD** [comment]
> Переделывая под этот формат, я понял, что работает это не так как задумывалось, потому что всё собирается в один JS файл и получается, что срабатывает несколько хендеров на каждой странице. Я так полагаю, что надо для каждой страницы теперь сделать отдельную генерацию скриптового JS файла, чтобы это работало как надо?

Все так, и в этом и суть. Инициализация по загрузке файла - плохая идея. Этот процесс нужно контролировать. И на конечной странице надо сделать скрипт который будет явно  инициализировать конечные модули.
