### ISSUE TITLE
Plug-in libraries

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/TOXIN#36]
Все подключаемые библиотеки должны быть максимально абстрагированы от реализации проекта. Т.е. они должны использоваться 'под капотом', но при этом не сильно влиять на код.
Т.е. если либы требуют подключения своих скриптов/стилей непосредственно - то для этого должна быть отдельная папка(для всех используемых либ), где будут лежат стили и скрипты этих либ.
А твои компоненты должны быть реализованы твоей архитектурой, но просто с использованием файлов либы.

Например, range slider должен быть по минимум связан с либой которую ты используешь - все стили и скрипты из блока range-slider нужно будет вынести.

Т е, например. ты хочешь подключить slider. Создаешь libs/slider в index.js ты пишешь класс Slider где описываешь инициализацию этого слайдера, slider.css - переопределяшь стили и т д. А в компоненте Slider ты подключаешь свою библиотеку. Нужно это что бы код твоего компонента не зависел от используемой библиотеки, и ты, в идеале, бы мог подключить другую библиотеку не меняя код самого компонента.

**Comment by Van4e3WT** [comment]
У меня имеются две подключаемые библиотеки. Одна из них подключена через npm, другую писал я и поэтому добавил минифицированные файлы. Под этот проект они обёрнуты в оболочку, которая кастомизируется в соответствии с нуждами (как js, так и scss). Как правильно сформировать файловую структуру? Как я понимаю, libs для npm пакетов должна быть внутри src, а для моего слайдера, который я писал? Создавать отдельную подпапку в public?

**Comment by mglknFSD** [comment]
Задача заключается в том что мы должны максимально абстрагировать проект от подключаемых библиотек. Т е мы для каждой библиотеки пишем некую прослойку, которую и используем в своих компонентах. Таким образом, если мы меняем библиотеку, это не окажет влияние на код компонентов, только на код этих прослоек.

**Comment by Van4e3WT** [comment]
> Задача заключается в том что мы должны максимально абстрагировать проект от подключаемых библиотек. Т е мы для каждой библиотеки пишем некую прослойку, которую и используем в своих компонентах. Таким образом, если мы меняем библиотеку, это не окажет влияние на код компонентов, только на код этих прослоек.

Так у меня эта прослойка реализована в src/libs/.. (datepicker-fork.js, multislider-v43-fork). Там же исправление стилей под свои нужды. Если говорить про формирование datepicker'a с некоторыми параметрами, то это объявлено в конкретном блоке, потому что именно там оно и инициализируется на странице (пример - блок twin-datepicker с twin-datepicker-init.js).

**Comment by mglknFSD** [comment]
> Так у меня эта прослойка реализована в src/libs/.. (datepicker-fork.js, multislider-v43-fork). Там же исправление стилей под свои нужды. Если говорить про формирование datepicker'a с некоторыми параметрами, то это объявлено в конкретном блоке, потому что именно там оно и инициализируется на странице (пример - блок twin-datepicker с twin-datepicker-init.js).

Т е она реализована таким образом, что если я захочу поменять на другой datapicker мне не придется трогать код компонента его использующего? У меня сложилось впечатление что это не реализовано. Хорошо, я посмотрю.

**Comment by mglknFSD** [comment]
Я не нашел кода который делает требуемые абстракции. Поясните мне пожалуйста как вы это реализовали.

**Comment by Van4e3WT** [comment]
> Я не нашел кода который делает требуемые абстракции. Поясните мне пожалуйста как вы это реализовали.

Пример на базе air-datepicker:
1) Подключаю сам плагин в файл datepicker-fork.js (для этого плагина это происходит обращением к конкретным файлам node_modules), этот datepicker-fork.js импортируется в js-файле точки входа сборщика. Подключение выполнено.
![image](https://user-images.githubusercontent.com/57857742/134807232-2c040ddf-7cd9-426b-b4ba-e9eaa446c993.png)
2) Изначально все инициализации были расположены в этом файле, но из соображений семантики и принадлежности были перенесены в сами блоки. Так, например, для двухдиапазонной даты используются параметры, отличные от стандартных и задаются в файле инициализации twin-datepicker-init.js.
![image](https://user-images.githubusercontent.com/57857742/134807361-a4b4e291-8c74-484c-928b-c57c345c72a3.png)
И для блока twin-datepicker файл twin-datepicker-init.js представляет своего рода абстракцию, когда нас не волнует внутренняя реализация, а идёт взаимодействие с заданным интерфейсом путём передачи объекта со свойствами в конструктор (условно, можно обновить плагин до новой версии, но при этом код не придётся менять, потому что идёт вызов всё того же конструктора и тех же параметров [а внесение изменений поведения в уже существующие свойства со стороны разрабочика пакета/плагина в любом случае повлечёт за собой негативные эффекты])

**Comment by mglknFSD** [comment]
Ну получается что у вас блок на прямую использует код библиотеки. Задание состоит в построении абстракции которая будет отделять код блока от кода библиотеки.

**Comment by Van4e3WT** [comment]
> Ну получается что у вас блок на прямую использует код библиотеки. Задание состоит в построении абстракции которая будет отделять код блока от кода библиотеки.

Правильно я понял, что нужно просто обернуть создание и инициализацию блока в класс? Т.е. если я создаю класс, в котором взаимодействую с кодом библиотеки. Является ли класс той самой абстракцией, которая отделяет код блока от кода библиотеки или нет?

**Comment by mglknFSD** [comment]
> > Ну получается что у вас блок на прямую использует код библиотеки. Задание состоит в построении абстракции которая будет отделять код блока от кода библиотеки.
> 
> Правильно я понял, что нужно просто обернуть создание и инициализацию блока в класс? Т.е. если я создаю класс, в котором взаимодействую с кодом библиотеки. Является ли класс той самой абстракцией, которая отделяет код блока от кода библиотеки или нет?

Я не понял ваш вопрос. Нужно сделать так, как написано вот тут https://github.com/Van4e3WT/TOXIN/issues/36#issue-999450940

**Comment by Van4e3WT** [comment]
> Я не понял ваш вопрос. Нужно сделать так, как написано вот тут

Я поэтому уточняю и пытаюсь понять, потому что не понял суть [вот этого](https://github.com/Van4e3WT/TOXIN/issues/36#issue-999450940) комментария. 

Предположим я подключаю датапикер, мне нужно иметь для разных блоков несколько разных (по параметрам) вариаций датапикеров. Мне нужно в `libs/datepicker` создать файлы с классами под каждый датапикер? и иметь по итогу что-то типо: 
```
libs
|  datepicker
|  |  datepicker-fork.js (или просто datepicker.js)
|  |  SoloDatepicker.js (класс с инициализацией такого-то пикера)
|  |  DoubleDatepicker.js (класс с инициализацией такого-то пикера)
|  |  OpenedDatepicker.js (класс с инициализацией такого-то пикера)
```  
а в блоке потом импортировать нужный класс?

**Comment by mglknFSD** [comment]
> 
> 
> > Я не понял ваш вопрос. Нужно сделать так, как написано вот тут
> 
> Я поэтому уточняю и пытаюсь понять, потому что не понял суть [вот этого](https://github.com/Van4e3WT/TOXIN/issues/36#issue-999450940) комментария.
> 
> Предположим я подключаю датапикер, мне нужно иметь для разных блоков несколько разных (по параметрам) вариаций датапикеров. Мне нужно в `libs/datepicker` создать файлы с классами под каждый датапикер? и иметь по итогу что-то типо:
> 
> ```
> libs
> |  datepicker
> |  |  datepicker-fork.js (или просто datepicker.js)
> |  |  SoloDatepicker.js (класс с инициализацией такого-то пикера)
> |  |  DoubleDatepicker.js (класс с инициализацией такого-то пикера)
> |  |  OpenedDatepicker.js (класс с инициализацией такого-то пикера)
> ```
> 
> а в блоке потом импортировать нужный класс?

Вы должны написать один класс который абстрагирует используемый датапикер. И все блоки, его использующие, должны использовать его.

**Comment by mglknFSD** [comment]
Вроде все хорошо, тоолько не надо в коде хранить обфусцированные артефакты. В папке src лежит только написанные тобою код. Если нет возможности установить код из npm, код библиотек помещаем в корень проекта в папку vendors или libs. 

![lib](https://user-images.githubusercontent.com/75975369/138589858-0c4cddf4-2fa5-4e33-bbca-474a4c8d41e3.jpg)
